import '../styles/globals.scss';
import type { Metadata } from 'next';
import { Provider } from '@/components/Provider';
import { NavMain } from '@/components/NavMain';
import { Main } from '@/components/Main';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'GitHub repositories explorer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased min-h-screen">
        <Provider>
          <NavMain />
          <Main>{children}</Main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
